### ISSUE TITLE
构建工具Todos

### ISSUE THREAD

**Issue by HairyRabbit** [Re-Rabbit/pandora#1]
## 遇到的问题
1. 多个项目共存时，完整构建一次需要耗时很久；
2. 在单个文件**改变**后，`gulp`需要对整个项目进行一次完整的构建；
3. 完整构建优化的方法之一是使用增量构建，`gulp-cache`之类的包。这样首次构建会将所有文件写入内存，在文件改变后直接从内存中读取。但遇到的问题是，如果a依赖b，b改变，a并不会被重新构建，原因是cache检测到a并没有发生任何变化，所以不会被重新构建；
4. 项目目录问题讨论；
5. 在运行一阵后明显会变慢；
## 讨论

解决问题三，想到了以下几种方案
### watch交由对应编译器自带的watcher

构建思路如下：

将Js文件变动时的构建任务交由webpack：

``` js
// webpack.config.js
{ watch: true }

// gulpfile.js
gulp.task('default', gulp.parallel(watchTask, webpackTask))
```

sass，nunjucks同理也可以采取这种方式。目前的JavaScript的构建就采用这个方式，特点是会启动多个server。
### 分析目标文件中的依赖路径，将用到的依赖包的径反转后写入缓存

构建思路如下：

在初次构建时将所有文件写入缓存，包括项目文件和依赖文件。并将项目文件用到的依赖也写入缓存

cache对象如下：

``` js
// 文件缓存
cache: [{
  "path/to/file": File Object
}]
// 依赖缓存
cache: {
  "lib1": [ file1, file2 ]
}
```

在文件变动时会出现两种情况：
- 项目文件变动时，分析文件中用到的依赖，如依赖有变动需要更新依赖缓存；
- 依赖文件变动时，从依赖缓存中读取引用到项目文件，并构建他们；
### 全部构建与部分构建，黑名单与工作空间

构建思路如下：

第二个方法有一个问题是，如果所有的项目文件都依赖了一个依赖文件，那么在这个依赖文件变动时相当于全部构建。所以想到了黑名单或工作空间来控制只构建部分文件。
#### 工作空间

工作空间即为对应的项目文件名。

初次构建是全部构建，并将所有文件写入缓存。在初次构建完成后，切换到默认的初始工作空间，如`index`，这时如果检测到文件变动，任务只构建当前项目的文件。

``` js
"pages/**/**/*.js" -> "pages/index/**/*.js"
```

这样需要在构建时先读取一个`workspace`的环境变量。并在工作空间改变时，重新构建对应项目下的文件。

难点是要如何触发改变工作空间。目前采用的方法是截取浏览器url下的第一级路径：

``` url
http://localhost:8080/{workspace}/
```

在路径跳转后将url发送到server经行匹配，从而改变workspace变量的值。但会出现如下几个问题：
1. 使用history跳转的页面会使用缓存304，这样请求并不会发送到服务器端。解决的方法是写入响应头no-cache；
2. 用browser-sync如果打开多个浏览器会来回触发切换事件，引起同步性循环。尚未解决；
#### 黑名单，白名单

如果说工作空间是自动匹配，那黑名单就是手动匹配。构建时将黑名单中的路径过滤掉，其他不变。但这里应该需要一个UI去配置黑名单。

所以说，如果项目文件变动就将对应的文件名记录在集合中，构建时只构建集合中的项目，通过UI去删除或增加。

**Comment by HairyRabbit** [comment]
@Cifer-Y :girl:

**Comment by HairyRabbit** [comment]
### Task: 路径处理
1. ~~通过globs统配路径~~
2. 反转路径 (not supports)

**Comment by 0x00-pl** [comment]
把node_module里的js拆出来试试?

**Comment by HairyRabbit** [comment]
### Task: 合并server

合并如下server:
1. ~~browserSync~~
2. ~~http-mock~~
3. ~~webpack-dev-server~~

Todo:
1. 编辑器server
2. 浏览器server

**Comment by HairyRabbit** [comment]
### Task: 测试
- [x] ~~初次打包，`src/**/index.styl -> tmp/**/index.css`~~
- [x] ~~监听，`src/**/index.styl -> tmp/**/index.css -> update BuildList`~~
- [x] ~~监听，`src/**/_test.styl -> tmp/**/index.css`~~
- [x] ~~监听，`src/lib/stylus_modules/mixin.styl -> tmp/**/index.css`~~
- [x] ~~监听，`src/lib/components/_test.styl -> tmp/**/index.css`~~
- [x] BuildList 超时，移除 (need add event listener)
- [x] ~~测试 all taker~~
- [x] ~~测试 browser~~
- [x] 合并 express， browser-sync，webpack-dev-server [ 1 / 3 ]
- [x] 测试 链接静态文件
